name: Deploy Madakoraa meet to Production

on:
  push:
    branches: 
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Pull the latest code from GitHub
            git pull origin main

            # Run your application directly (adjust the command as needed)
            npm install  # Add this line if your project has Node.js dependencies
            nohup npm start    # Replace this with the actual command to start your application
